# Generated by Django 4.0.5 on 2022-07-10 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('hora', models.CharField(max_length=13, verbose_name='Hora')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre')),
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('numero', models.CharField(max_length=50, verbose_name='Numero')),
                ('patente', models.CharField(max_length=7, verbose_name='Patente')),
                ('estacionamiento', models.CharField(max_length=50, verbose_name='Estacionamiento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
